# Copyright 2019-2020 Fujitsu Laboratories Ltd.
# SPDX-License-Identifier: Apache-2.0
version: "3.4"

services:
  geth1:
    container_name: geth1
    image: geth-testnet:latest
    build:
      context: .
    ports:
      - "8545:8545" #uncomment this line to enable JSON-RPC access from outside of network
    networks:
      - geth1net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  geth1net:
    external: true
